In [2]:
import numpy as np

In [3]:
# creating numpy array

In [6]:
my_list=[1,2,3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
x=np.array(my_list)

In [9]:
type(x)

numpy.ndarray

In [10]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.linspace(0,11,6)

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.random.rand(3,3)

array([[0.40703637, 0.11719321, 0.67601082],
       [0.76781129, 0.61798075, 0.31178492],
       [0.25743506, 0.75254055, 0.91548873]])

In [41]:
np.random.rand(3)

array([0.94042577, 0.42447307, 0.0142785 ])

In [42]:
np.random.randn(3,3)

array([[-1.17358109, -0.57236938,  1.14275028],
       [-0.57742382,  0.84978015,  0.70187981],
       [-1.18740466,  2.45419866,  0.28205223]])

In [43]:
np.random.randn(3)

array([ 0.75125631, -0.38996327,  0.13724891])

In [47]:
np.random.randint(1,100,3)

array([36, 48,  5])

In [50]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr.shape

(25,)

In [56]:
arr.reshape(5,5).shape

(5, 5)

In [57]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [58]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
arr.dtype

dtype('int64')

In [60]:
ranarr

array([ 3, 49, 40, 15, 23,  1, 36,  4, 23, 16])

In [62]:
ranarr.max()

49

In [63]:
ranarr.argmax()

1

In [64]:
ranarr.argmin()

5

In [65]:
arr = np.arange(0,10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
arr/arr

/Users/tamerhousseinhag/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/arr

/Users/tamerhousseinhag/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [72]:
arr**4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [73]:
arr+200

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209])

In [74]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [75]:
np.max(arr)

9

In [76]:
np.min(arr)

0

In [77]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [78]:
arr.max()

9

In [80]:
np.log(arr)

/Users/tamerhousseinhag/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [81]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [83]:
arr[:3]

array([0, 1, 2])

In [84]:
arr[4:3]

array([], dtype=int64)

In [85]:
arr[3:4]

array([3])

In [86]:
arr[6:3]

array([], dtype=int64)

In [87]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [88]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [89]:
arr=np.arange(0,11,1)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
slice_of_arr=arr[0:6]

In [93]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [94]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [95]:
slice_of_arr[:]=88

In [96]:
slice_of_arr

array([88, 88, 88, 88, 88, 88])

In [97]:
arr

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [98]:
#mat[r,c]
#mat[r][c]

In [101]:
mat=np.array([[5,11,12],[22,33,44],[56,67,78]])

In [102]:
mat

array([[ 5, 11, 12],
       [22, 33, 44],
       [56, 67, 78]])

In [103]:
mat[0]

array([ 5, 11, 12])

In [104]:
mat[2]

array([56, 67, 78])

In [105]:
mat[0][1]

11

In [107]:
mat[0,1]

11

In [108]:
mat

array([[ 5, 11, 12],
       [22, 33, 44],
       [56, 67, 78]])

In [109]:
mat[1,2]

44

In [110]:
mat

array([[ 5, 11, 12],
       [22, 33, 44],
       [56, 67, 78]])

In [120]:
mat[1:3,1:3]

array([[33, 44],
       [67, 78]])

In [121]:
mat[:2,:1]

array([[ 5],
       [22]])

In [122]:
mat[:2,1:]

array([[11, 12],
       [33, 44]])

In [136]:
mat[1:,:2]

array([[22, 33],
       [56, 67]])

In [137]:
#conditional selection

In [138]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
arr<4

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [140]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [141]:
bool_arr=arr>4

In [143]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [144]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [145]:
arr[arr<=3]

array([1, 2, 3])