In [1]:
# Part I

In [2]:
import numpy as np

In [3]:
mylist=[1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
nested_list=[[1,2],[3,4],[5,6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [15]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(3)

array([0.74774317, 0.68153652, 0.1041054 ])

In [17]:
np.random.rand(3,4)

array([[0.05742697, 0.87235963, 0.4512329 , 0.17081825],
       [0.27193098, 0.65592797, 0.95465824, 0.94544153],
       [0.80686607, 0.48198411, 0.6501252 , 0.71095243]])

In [18]:
np.random.randn(5,2)

array([[-0.33590918,  0.71488885],
       [-1.10505879, -0.5085864 ],
       [ 0.62071148,  0.13413672],
       [ 1.16648667, -1.09285422],
       [-0.38120042, -0.48845684]])

In [19]:
np.random.normal(5,2,10)

array([8.20716463, 4.87181515, 8.44829645, 2.14802404, 3.76885219,
       3.70861962, 7.11722912, 3.39085527, 1.23636988, 2.49762601])

In [20]:
np.random.normal(1)

2.4027765425989482

In [21]:
np.random.randint(1,100,6)

array([26, 74, 88, 47, 11, 86])

In [22]:
np.random.seed(5000)
xn=np.random.rand(4)
xn

array([0.22904787, 0.36066976, 0.727653  , 0.1126678 ])

In [23]:
xn

array([0.22904787, 0.36066976, 0.727653  , 0.1126678 ])

In [24]:
xn

array([0.22904787, 0.36066976, 0.727653  , 0.1126678 ])

In [68]:
arr=np.arange(36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [74]:
arrnd=np.random.randint(0,25,24)
arrnd

array([16,  0,  1, 20, 19, 22, 20, 19,  6,  8,  7, 20, 14,  0, 18, 16, 17,
       19, 18,  9,  6,  0, 10, 10])

In [70]:
arr.shape

(36,)

In [72]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [78]:
arr.reshape(9,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [31]:
arrnd

array([ 0, 21, 19,  3, 17, 14, 10,  3,  0, 20,  5,  2, 12, 12, 13, 16, 20,
        1, 13,  7,  0,  7, 16, 24])

In [32]:
arrnd.max()

24

In [33]:
arrnd.argmax()

23

In [34]:
arrnd.argmin()

0

In [35]:
arrnd.dtype

dtype('int64')

In [36]:
# Part II

In [37]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[9]

9

In [39]:
arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [41]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr=np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr=arr[0:5]

In [47]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr[:]=99

In [50]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [57]:
arr_copy=arr.copy()

In [60]:
arr_copy[:]=0

In [61]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d.shape

(3, 3)

In [81]:
arr_2d[0,1]

10

In [82]:
arr_2d[1,2]

30

In [87]:
arr_2d[1]

array([20, 25, 30])

In [90]:
arr_2d[1:2]

array([[20, 25, 30]])

In [93]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [94]:
arr_2d[2:]

array([[35, 40, 45]])

In [95]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [96]:
arr_2d[2:,1:]

array([[40, 45]])

In [97]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [98]:
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [99]:
arr_2d[2:,:1]

array([[35]])

In [108]:
arr_2d[:3,:1]

array([[ 5],
       [20],
       [35]])

In [112]:
arr_2d[:3,1:2]

array([[10],
       [25],
       [40]])

In [114]:
arr_2d[:3,2:3]

array([[15],
       [30],
       [45]])

In [115]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [117]:
arr_x=np.arange(1,11)
arr_x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
bool_arrx=arr_x > 4

In [125]:
bool_arrx

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [128]:
arr_x[bool_arrx]

array([ 5,  6,  7,  8,  9, 10])

In [129]:
arr_x[arr_x>4]

array([ 5,  6,  7,  8,  9, 10])

In [130]:
# Part III

In [133]:
arry=np.arange(0,10)
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
arry+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [135]:
arry-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [136]:
arry+arry

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
arry**6

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649,
       262144, 531441])

In [139]:
pow(arry,6)

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649,
       262144, 531441])

In [140]:
pow(arry,arry)

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [141]:
arry-arry

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [142]:
arry*arry

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [150]:
arryy=arry[1:]
arryy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
arryy/arryy

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [155]:
np.sqrt(arry)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [156]:
np.sin(arry)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [157]:
np.tan(arry)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [158]:
np.cos(arry)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [159]:
np.exp(arry)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [160]:
np.log(arryy)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [161]:
arry.mean()

4.5

In [162]:
arry.max()

9

In [163]:
arry.sum()

45

In [164]:
arry.var()

8.25

In [165]:
arry.std()

2.8722813232690143

In [170]:
arr2D=arry.reshape(5,2)

In [171]:
arr2D

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [172]:
arr2D.sum()

45

In [173]:
arr2D.sum(axis=0)

array([20, 25])

In [174]:
arr2D.sum(axis=1)

array([ 1,  5,  9, 13, 17])