In [1]:
print("Hello World")

Hello World


In [2]:
def HelloWorldXY(x,y):
  if (x<10):
    print("HelloWorld, x was < 10")
  elif (x<10):
    print("HelloWorld, x was >= 10 but < 20")
  else:
    print("Hello World, x was >=20")
  return x+y

for i in range(8,25,5): 
  print("---Now running with i: {}".format(i))
  r=HelloWorldXY(i,i)
  print("Result from HelloWorld: {}".format(i,r))

---Now running with i: 8
HelloWorld, x was < 10
Result from HelloWorld: 8
---Now running with i: 13
Hello World, x was >=20
Result from HelloWorld: 13
---Now running with i: 18
Hello World, x was >=20
Result from HelloWorld: 18
---Now running with i: 23
Hello World, x was >=20
Result from HelloWorld: 23


In [3]:
print(HelloWorldXY(1,2))

print(HelloWorldXY(5,20))

HelloWorld, x was < 10
3
HelloWorld, x was < 10
25


In [4]:
print("iteration over the items")
for i in range(2):
  print(i)
# or
print("iteration over the items")
i=0
while i<2:
  print(i)
  i+=1

iteration over the items
0
1
iteration over the items
0
1


In [5]:
print("stdr key words")
while True:
  print("Entered while")
  break

stdr key words
Entered while


In [6]:
import numpy as np

In [7]:
a=np.array(["Hello", "World"])
a=np.append(a, "!")
print("current array: {}".format(a))
print("Printing each element")
for i in a:
    print(i)

print("Printing each element and their index")
for i,e in enumerate(a):
    print("Index: {}, was: {}".format(i,e))

current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!
Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [8]:
print("Showing some basic math on arrays")
b=np.array([0,1,4,2,3])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max Index: {}".format(np.argmax(b)))

Showing some basic math on arrays
Max: 4
Average: 2.0
Max Index: 2


In [9]:
print("You can print the type of anything")
print("Type of b: {},Type of b[0]: {}".format(type(a),type(a[0])))

You can print the type of anything
Type of b: <class 'numpy.ndarray'>,Type of b[0]: <class 'numpy.str_'>


In [10]:
print("Use numpy to create a [3,3] dimension array with random number")
c=np.random.rand(3,3)
print(c)

Use numpy to create a [3,3] dimension array with random number
[[0.54168172 0.93632114 0.71412858]
 [0.24738693 0.99968153 0.19433359]
 [0.55668681 0.78118115 0.89201058]]


In [11]:
print("You can print the dimensions of arrays")
print("shape of a: {}".format(a.shape))
print("shape of b: {}".format(b.shape))
print("shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and [0,1,2] to specify lists")

You can print the dimensions of arrays
shape of a: (3,)
shape of b: (5,)
shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and [0,1,2] to specify lists
