In [1]:
# Part I

In [2]:
# Linear interpolation

In [100]:
import numpy as np

In [4]:
#time=np.arange(0,101,20)
#time

#tim=np.linspace(0,100,6)
#tim

In [5]:
temp=[26,48.6,61.6,71.2,74.8,75.2]
temp

[26, 48.6, 61.6, 71.2, 74.8, 75.2]

In [16]:
y=lambda xp,x1,x2,y1,y2: y1+(((y2-y1)/(x2-x1))*(xp-x1))
y(50,40,60,61.6,71.2)

66.4

In [20]:
time=np.arange(0,101,20)
temp=[26,48.6,61.6,71.2,74.8,75.2]

def y(xp, x, y):
    for i,xi in enumerate(x):
        if xp<xi: 
            return y[i-1]+(((y[i]-y[i-1])/(x[i]-x[i-1]))*(xp-x[i-1]))
    else:
        print('Given x-value is out of range')
        
temp50=y(50,time,temp)
print('the temperature = %f' %temp50)

the temperature = 66.400000


In [17]:
# Part II

# Lagrange's Method

In [23]:
x=np.linspace(0,100,6)
y=[26,48.6,61.6,71.2,74.8,75.2]

m=len(x) # length of the x list
n=m-1
xp=float(input('Enter x: '))
yp=0

for i in range(n+1):
    L=1
    for j in range(n+1):
        if j!=i:
            L*=(xp-x[j])/(x[i]-x[j])
    yp+=y[i]*L
print ('For x=%.1f, y=%.1f' %(xp,yp))

Enter x: 50
For x=50.0, y=66.9


In [61]:
# Part II

# Newton's intepolation Method

In [56]:
x=[0,1.5,2.8,4.4,6.1,8]
y=[0,0.9,2.5,6.6,7.7,8]

n=len(x)-1
Dy=np.zeros((n+1,n+1))
Dy[:,0]=y

for j in range(n):
    for i in range(j+1,n+1):
        Dy[i,j+1]=((Dy[i,j]-Dy[j,j])/(x[i]-x[j]))
Dy

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.9       ,  0.6       ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 2.5       ,  0.89285714,  0.22527473,  0.        ,  0.        ,
         0.        ],
       [ 6.6       ,  1.5       ,  0.31034483,  0.05316881,  0.        ,
         0.        ],
       [ 7.7       ,  1.26229508,  0.14397719, -0.02463562, -0.04576731,
         0.        ],
       [ 8.        ,  1.        ,  0.06153846, -0.03148774, -0.02351571,
         0.01171137]])

In [60]:
xp=float(input('Enter x: ')) 
yp=Dy[0,0]
for i in range(n):
    xprod=1
    for j in range(i+1):
        xprod*=(xp-x[j])
    yp+=xprod*Dy[i+1,i+1]
print('For x=%.1f, y=%.1f' %(xp,yp))

Enter x: 6.1
For x=6.1, y=7.7


In [63]:
# Part IV

# Linear Regression (for loop)

In [98]:
x=np.linspace(3,8,6)
y=[0,7,17,26,35,45]

n=len(x)
sum_x=sum_y=sum_x2=sum_xy=0

for i in range(n):
    sum_x+=x[i]
    sum_y+=y[i]
    sum_x2+=x[i]**2
    sum_xy+=x[i]*y[i]

x_mean=sum_x/n
y_mean=sum_y/n

a=(((y_mean*sum_x2)-(x_mean*sum_xy))/(sum_x2-(n*x_mean)))
b=((sum_xy-(x_mean*sum_y))/(sum_x2-(n*x_mean)))

print('The straight line equation', 'y=(%.2f)+(%.2f)*x' %(a,b))

The straight line equation y=(-2.98)+(0.96)*x


In [95]:
# Part V

# Linear Regression (Numpy arrays)

In [102]:
x=np.linspace(3,8,6)
y=[0,7,17,26,35,45]

n=len(x)

a=(((np.mean(y)*sum(pow(x,2)))-(np.mean(x)*sum(x*y)))/(sum(pow(x,2))-(n*np.mean(x))))
b=((sum(x*y)-(np.mean(x)*sum(y)))/(sum(pow(x,2))-(n*np.mean(x))))

print('The straight line equation', 'y=(%.2f)+(%.2f)*x' %(a,b))

The straight line equation y=(-2.98)+(0.96)*x


In [107]:
# Part VI

# Polynomial fit (Curve Fitting)

In [115]:
x=np.linspace(0,5,6)
y=[2,8,14,28,39,62]

m=len(x)
n=2
A=np.zeros((n+1,n+1))
B=np.zeros(n+1)
a=np.zeros(n+1)

for row in range(n+1):
    for col in range(n+1):
        if row==0 and col==0:
            A[row,col]=m
            continue
        A[row,col]=np.sum(pow(x,(row+col)))
    B[row]=np.sum(y*pow(x,row))

a=np.linalg.solve(A,B)
print('The polynomial is :','f(x)= \t %f' %a[0])
for i in range(1,n+1):
    print('\t %+f x^%d' %(a[i],i))

The polynomial is : f(x)= 	 2.678571
	 +2.253571 x^1
	 +1.875000 x^2


In [116]:
x=np.linspace(0,5,6)
y=[2,8,14,28,39,62]

m=len(x)
n=3
A=np.zeros((n+1,n+1))
B=np.zeros(n+1)
a=np.zeros(n+1)

for row in range(n+1):
    for col in range(n+1):
        if row==0 and col==0:
            A[row,col]=m
            continue
        A[row,col]=np.sum(pow(x,(row+col)))
    B[row]=np.sum(y*pow(x,row))

a=np.linalg.solve(A,B)
print('The polynomial is :','f(x)= \t %f' %a[0])
for i in range(1,n+1):
    print('\t %+f x^%d' %(a[i],i))

The polynomial is : f(x)= 	 1.928571
	 +5.678571 x^1
	 -0.000000 x^2
	 +0.250000 x^3


In [117]:
# Part VII

# Revisiting all parts with scipy

In [118]:
from scipy.interpolate import interp1d, lagrange

In [122]:
time=np.arange(0,101,20)
temp=[26,48.6,61.6,71.2,74.8,75.2]

f=interp1d(time,temp)
print(f(50))

66.4


In [123]:
f=interp1d(time,temp,'quadratic')
print(f(50))

66.95208333333332


In [125]:
f=interp1d(time,temp,'cubic')
print(f(50))

66.945


In [124]:
L=lagrange(time,temp)
print(L(50))

66.94765624999957


In [129]:
L=lagrange(time,temp)
print(L)

           5             4             3           2
3.698e-08 x - 9.688e-06 x + 0.0009219 x - 0.04463 x + 1.725 x + 26


In [130]:
from scipy.misc import derivative

In [135]:
from scipy.stats import linregress

In [136]:
from scipy.optimize import curve_fit

In [137]:
x=np.linspace(3,8,6)
y=[0,7,17,26,35,45]

linregress(x,y)

LinregressResult(slope=9.085714285714285, intercept=-28.3047619047619, rvalue=0.9990651680982869, pvalue=1.3104575468971522e-06, stderr=0.19656921371950828)

In [138]:
linregress(x,y).slope

9.085714285714285

In [139]:
linregress(x,y).intercept

-28.3047619047619

In [140]:
print('The straight line equation', 'y=(%.2f)+(%.2f)*x' %(linregress(x,y).slope,linregress(x,y).intercept))

The straight line equation y=(9.09)+(-28.30)*x


In [151]:
x=np.linspace(0,5,6)
y=[2,8,14,28,39,62]

f=lambda x,a0,a1,a2: a0+a1*x+a2*pow(x,2)

curve_fit(f,x,y)
(a,b)=curve_fit(f,x,y)
(a,b)

(array([2.67857143, 2.25357143, 1.875     ]),
 array([[ 3.78835029, -2.71772967,  0.41177724],
        [-2.71772967,  3.35186676, -0.61766587],
        [ 0.41177724, -0.61766587,  0.12353317]]))

In [150]:
print(a)

[2.67857143 2.25357143 1.875     ]


In [152]:
print(b)

[[ 3.78835029 -2.71772967  0.41177724]
 [-2.71772967  3.35186676 -0.61766587]
 [ 0.41177724 -0.61766587  0.12353317]]


In [155]:
f=lambda x,a0,a1,a2,a3: a0+a1*x+a2*pow(x,2)+a3*pow(x,3)

curve_fit(f,x,y)

(a,b)=curve_fit(f,x,y)
(a,b)

(array([ 1.92857143e+00,  5.67857143e+00, -2.17847962e-12,  2.50000000e-01]),
 array([[ 3.68225352e+00, -1.81170252e+00, -7.83525133e-06,
          4.62383516e-02],
        [-1.81170252e+00,  1.75673872e+00, -2.18158095e-05,
         -6.34981147e-02],
        [-7.83525133e-06, -2.18158095e-05,  2.41729418e-09,
          1.07542719e-06],
        [ 4.62383516e-02, -6.34981147e-02,  1.07542719e-06,
          2.73863476e-03]]))

In [156]:
print(a)

[ 1.92857143e+00  5.67857143e+00 -2.17847962e-12  2.50000000e-01]


In [157]:
print(b)

[[ 3.68225352e+00 -1.81170252e+00 -7.83525133e-06  4.62383516e-02]
 [-1.81170252e+00  1.75673872e+00 -2.18158095e-05 -6.34981147e-02]
 [-7.83525133e-06 -2.18158095e-05  2.41729418e-09  1.07542719e-06]
 [ 4.62383516e-02 -6.34981147e-02  1.07542719e-06  2.73863476e-03]]
