In [1]:
# Part I

# Gauss Elemination Method

In [134]:
import numpy as np

In [69]:
a=np.array([[2,7,-1,3,1],
            [2,3,4,1,7],
            [6,2,-3,2,-1],
            [2,1,2,-1,2],
            [3,4,1,-2,1]],float)

b=np.array([[5,7,2,3,4]],float).reshape(5,1)

n=len(b)
x=np.zeros(n,float)

#Elemination
for k in range (n-1): # row before the last
    for i in range(k+1,n): # until last row
        factor=a[k,k]/a[i,k]
        b[i]=b[k]-factor*b[i]
        for j in range (k,n):
            a[i,j]=a[k,j]-factor*a[i,j]
#Back-Substitution
x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
    terms=0
    for j in range(i+1,n):
        terms+=a[i,j]*x[j]
    x[i]=(b[i]-terms)/a[i,i]

print('The solution of the system: ')
print(x)

The solution of the system: 
[0.44444444 0.55555556 0.66666667 0.22222222 0.22222222]


In [73]:
a=np.array([[0,7,-1,3,1],
            [2,3,4,1,7],
            [6,2,0,2,-1],
            [2,1,2,0,2],
            [3,4,1,-2,1]],float)

b=np.array([[5,7,2,3,4]],float).reshape(5,1)

n=len(b)
x=np.zeros(n,float)

#Elemination
for k in range (n-1): # row before the last
    if a[k,k]==0:
        for j in range(n):
            a[k,j],a[k+1,j]=a[k+1,j],a[k,j]
        b[k],b[k+1]=b[k+1],b[k]
    for i in range(k+1,n): # until last row
        if a[i,k]==0:
            continue
        factor=a[k,k]/a[i,k]
        b[i]=b[k]-factor*b[i]
        for j in range (k,n):
            a[i,j]=a[k,j]-factor*a[i,j]
#Back-Substitution
x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
    terms=0
    for j in range(i+1,n):
        terms+=a[i,j]*x[j]
    x[i]=(b[i]-terms)/a[i,i]

print('The solution of the system: ')
print(x)

The solution of the system: 
[-0.21705426  1.07751938  1.48837209  0.41860465 -0.31007752]


In [59]:
a=np.array([[1,-2,1],
            [-1,4,2],
            [3,1,-1]],float)

b=np.array([[14,1,-7]],float).reshape(3,1)

n=len(b)
x=np.zeros(n,float)

#Elemination
for k in range (n-1): # row before the last
    for i in range(k+1,n): # until last row
        factor=a[k,k]/a[i,k]
        b[i]=b[k]-factor*b[i]
        for j in range (k,n):
            a[i,j]=a[k,j]-factor*a[i,j]
#Back-Substitution
x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
    terms=0
    for j in range(i+1,n):
        terms+=a[i,j]*x[j]
    x[i]=(b[i]-terms)/a[i,i]

print('The solution of the system: ')
print(x)

The solution of the system: 
[ 1. -3.  7.]


In [62]:
a=np.array([[1,1,-2],
            [3,-2,1],
            [2,-3,3]],float)

b=np.array([[0,0,0]],float).reshape(3,1)

n=len(b)
x=np.zeros(n,float)

#Elemination
for k in range (n-1): # row before the last
    for i in range(k+1,n): # until last row
        factor=a[k,k]/a[i,k]
        b[i]=b[k]-factor*b[i]
        for j in range (k,n):
            a[i,j]=a[k,j]-factor*a[i,j]
#Back-Substitution
x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
    terms=0
    for j in range(i+1,n):
        terms+=a[i,j]*x[j]
    x[i]=(b[i]-terms)/a[i,i]

print('The solution of the system: ')
print(x)

The solution of the system: 
[ 0.  0. -0.]


In [63]:
a=np.array([[1,1,-2],
            [3,-2,1],
            [2,-3,3]],float)

b=np.array([[1,-15,-16]],float).reshape(3,1)

n=len(b)
x=np.zeros(n,float)

#Elemination
for k in range (n-1): # row before the last
    for i in range(k+1,n): # until last row
        factor=a[k,k]/a[i,k]
        b[i]=b[k]-factor*b[i]
        for j in range (k,n):
            a[i,j]=a[k,j]-factor*a[i,j]
#Back-Substitution
x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
    terms=0
    for j in range(i+1,n):
        terms+=a[i,j]*x[j]
    x[i]=(b[i]-terms)/a[i,i]

print('The solution of the system: ')
print(x)

The solution of the system: 
[-2.6  3.6 -0. ]


In [64]:
a=np.array([[1,1,-2],
            [3,-2,1],
            [2,-3,3]],float)

b=np.array([[1,-15,2]],float).reshape(3,1)

n=len(b)
x=np.zeros(n,float)

#Elemination
for k in range (n-1): # row before the last
    for i in range(k+1,n): # until last row
        factor=a[k,k]/a[i,k]
        b[i]=b[k]-factor*b[i]
        for j in range (k,n):
            a[i,j]=a[k,j]-factor*a[i,j]
#Back-Substitution
x[n-1]=b[n-1]/a[n-1,n-1]
for i in range(n-2,-1,-1):
    terms=0
    for j in range(i+1,n):
        terms+=a[i,j]*x[j]
    x[i]=(b[i]-terms)/a[i,i]

print('The solution of the system: ')
print(x)

The solution of the system: 
[-8.10647933e+15 -1.89151184e+16 -1.35107989e+16]


In [74]:
# Part II

# Jacobi's Method

In [115]:
a=np.array([[4,1,2,-1],
            [3,6,-1,2],
            [2,-1,5,-3],
            [4,1,-3,-8]],float)

b=np.array([[2,-1,3,2]],float).reshape(4,1)

n=len(b)

#n=np.shape(b)
x=np.full(n,1.0,float) # initial value of x 1.0
xnew=np.empty(n,float)

iterlimit=101
tolerance=1.0e-6

#Iterations
for iteration in range(iterlimit):
    for i in range ((n)):
        s=0
        for j in range((n)):
            if j!=i:
                s+=a[i,j]*x[j]
        xnew[i]=-1/a[i,i]*(s-b[i])
    if(abs(xnew-x)<tolerance).all():
        break
    else:
        x=np.copy(xnew)
        
print('The solution: ')
print(x)
print('Number of iterations %d '%(iteration))

The solution: 
[ 0.3650067  -0.23378439  0.28506845 -0.20362079]
Number of iterations 30 


In [104]:
# Part III

# Gauss-Seidel Method

In [120]:
a=np.array([[2,-1,5,-3],
            [4,1,2,-1],
            [4,1,-3,-8],
            [3,6,-1,2]],float)

b=np.array([[3,2,2,-1]],float).reshape(4,1)

n=len(b)

x=np.full(n,1.0,float) # initial value of x 1.0
xdiff=np.empty(n,float)

iterlimit=101
tolerance=1e-6

#Iterations
for iteration in range(iterlimit):
    for i in range (n):
        s=0
        for j in range(n):
            if j!=i:
                s+=a[i,j]*x[j]
        xnew=-1/a[i,i]*(s-b[i])
        xdiff=abs(xnew-x[i])
        x[i]=xnew
    if(xdiff<tolerance).all():
        break
        
print('The solution: ')
print(x)
print('Number of iteration %d '%(iteration))

The solution: 
[ 1.08639576e+111 -3.49452443e+111 -1.40426166e+111  8.15184880e+111]
Number of iteration 100 


In [119]:
# Part IV

# Diagonal dominance

In [89]:
a=np.array([[4,1,2,-1],
            [3,6,-1,2],
            [2,-1,5,-3],
            [4,1,-3,-8]],float)

b=np.array([[2,-1,3,2]],float).reshape(4,1)

n=len(b)

x=np.full(n,1.0,float) # initial value of x 1.0
xdiff=np.empty(n,float)

iterlimit=101
tolerance=1e-6

#Iterations
for iteration in range(iterlimit):
    for i in range (n):
        s=0
        for j in range(n):
            if j!=i:
                s+=a[i,j]*x[j]
        xnew=-1/a[i,i]*(s-b[i])
        xdiff=abs(xnew-x[i])
        x[i]=xnew
    if(xdiff<tolerance).all():
        break
        
print('The solution: ')
print(x)
print('Number of iteration %d '%(iteration))

array([3, 4, 5, 6, 7, 8, 9])

In [121]:
# Part V

# Gauss-Jordan Method

In [125]:
def gaussjordan(a,b):
    a=np.array(a,float)
    b=np.array(b,float)
    n=len(b)
    
    #Main loop 
    for k in range (n):
        #Partial Pivoting
        if np.fabs(a[k,k])<1.0e-12:
            for i in range(k+1,n):
                if np.fabs(a[i,k])>np.fabs(a[k,k]):
                    a[[k,i]]=a[[i,k]]
                    b[[k,i]]=b[[i,k]]
                    break
        #Division of pivot row
        pivot=a[k,k]
        a[k]/=pivot
        b[k]/=pivot
        #Elemination loop
        for i in range(n):
            if i==k or a[i,k]==0:
                continue
            factor=a[i,k]            
            a[i]-=factor*a[k]
            b[i]-=factor*b[k]
    return b,a

a=[[0,2,0,1],[2,2,3,2],[4,-3,0,1],[6,1,-6,-5]]
b=[0,-2,-7,6]

X,A=gaussjordan(a,b)

print('The solution: ')
print(X)
print('The transformed [a]: ')
print(A)

The solution: 
[-0.5         1.          0.33333333 -2.        ]
The transformed [a]: 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [-0. -0. -0.  1.]]


In [126]:
# Part VI

# Solutions in NumPy & SciPy

In [140]:
from scipy.linalg import solve, inv

In [141]:
a=np.array([[2,-1,5,-3],
            [4,1,2,-1],
            [4,1,-3,-8],
            [3,6,-1,2]],float)

b=np.array([[3,2,2,-1]],float).reshape(4,1)

x=solve(a,b)
x

array([[ 0.36500754],
       [-0.23378582],
       [ 0.28506787],
       [-0.20361991]])

In [144]:
a=np.array([[2,-1,5,-3],
            [4,1,2,-1],
            [4,1,-3,-8],
            [3,6,-1,2]],float)

b=np.array([[3,2,2,-1]],float).reshape(4,1)

x=np.dot(inv(a),b)
x

array([[ 0.36500754],
       [-0.23378582],
       [ 0.28506787],
       [-0.20361991]])

In [156]:
a=np.array([[2,-1,5,-3],
            [4,1,2,-1],
            [4,1,-3,-8],
            [3,6,-1,2]],float)

b=np.array([[3,2,2,-1]],float).reshape(4,1)

x=np.linalg.solve(a,b)
x

array([[ 0.36500754],
       [-0.23378582],
       [ 0.28506787],
       [-0.20361991]])